"""Public utility surface used by the orchestrator and tests."""

from .cache import (StageArtifacts, canonical_summary_path,
                    cleanup_orchestrator_stage_outputs, collect_round_summaries,
                    ensure_static_snapshot, ingest_round_to_cache, load_round_index,
                    parse_round_summary, round_cache_dir, round_cache_hit, round_index_path,
                    stage_artifacts_for_round, static_cache_dir, upsert_round_index,
                    validate_static_records)
from .config import (clamp_parallelism, load_config, minimal_validate,
                     parse_rounds_spec, resolve_path, set_round, strip_orchestration,
                     write_config)
from .hashing import (compute_exp_hash, compute_ns3_stage_hash, compute_round_key,
                      compute_static_key, effective_round_state)
from .orchestration import (apply_round_variation, load_participation_matrix,
                            participation_file_from_orch, selection_pct_from_orch,
                            validate_participation_matrix)
from .reporting import (export_summary_detailed_csv, export_summary_json, finalize_summary_df,
                        load_external_results)
from .records import (cleanup_logs, cleanup_records, list_records_compact,
                      refresh_legacy_records_index)

__all__ = [
    "StageArtifacts",
    "apply_round_variation",
    "canonical_summary_path",
    "cleanup_orchestrator_stage_outputs",
    "clamp_parallelism",
    "cleanup_logs",
    "cleanup_records",
    "collect_round_summaries",
    "compute_exp_hash",
    "compute_ns3_stage_hash",
    "compute_round_key",
    "compute_static_key",
    "effective_round_state",
    "ensure_static_snapshot",
    "export_summary_detailed_csv",
    "export_summary_json",
    "finalize_summary_df",
    "ingest_round_to_cache",
    "list_records_compact",
    "load_config",
    "load_external_results",
    "load_participation_matrix",
    "load_round_index",
    "minimal_validate",
    "parse_round_summary",
    "parse_rounds_spec",
    "participation_file_from_orch",
    "resolve_path",
    "refresh_legacy_records_index",
    "round_cache_dir",
    "round_cache_hit",
    "round_index_path",
    "selection_pct_from_orch",
    "set_round",
    "stage_artifacts_for_round",
    "static_cache_dir",
    "strip_orchestration",
    "upsert_round_index",
    "validate_static_records",
    "validate_participation_matrix",
    "write_config",
]
